sudo: required

dist: trusty

language: node_js

services:
  - docker

node_js:
  - "10.8.0"

addons:
  sonarcloud:
    organization: "indicium"
    token: $SONAR_TOKEN

cache:
  npm: true

install:
  - npm install
  - npm run generate

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
  - echo "Skipping tests"
  - npm run build

after_success:
  - docker build -t indicium:website .
