sudo: required

dist: trusty

language: node_js

services:
  - docker

git:
  depth: false

node_js:
  - "10.8.0"

env:
  global:
    - secure: "QykKHxCXS3At+/EoaVNPOfP7r74h2zrbtI3/8PO6AJSfGrpKzWPgyUcoWhIk/rTHesqg+3tdf8Vk+yNh+9vKKEVktj2FVtG6LZVeiVd0gBl2EYO9t4271DYTfsWonGmN3W7owej+brtYLyJ7Ov9Hv15hJpzLGjn0yDw5Y/K7DuLGOnqqUcyRLPyw99OgojgLp3gh91+VV4aGhzYKIYYOoVA648sZyfqYhnTzjDs4I/w/Xx+vidac3n4e3nhQ3lZuLwlv9dOeVgpNxQKuM0rXKMCztnFhTS8MgpmCQ/vZ8SERbNp7CTQ59ht3/KvbVVwe6rVCB1cyvtbb01PiJEMBtb3NRsbGEGycbMXOaHu8zuQ/Gj7yPPgHmFflOyQ+jftSrUwrggtNRpyLZam8TZpyDt+DWZ/U67ps8iC4qAa9KRIW5ZfX7SYaGWzpmccxNqxFKeti1UqRK0KPoYEOLKGnlYawa/L2BUZ0ZondNoMF59r89rBCbwONb8jY8qfzIL7HADfU7ZwOQP8HcjkzkiRVzY9PHwHkgS3IxLKg69ctyXv/RVT4qHbQrS/tRdScS6hnxPQSLRXBMvYTPKParUkKTMaCI9AxT3biixjJMwQaLaiucm1AtuI073kYA5edjhVNYwGloZJvwA+qf7QUxxXD/vcfYnFTglLiaWBWGyRZbGw="
    - secure: "XsfbkDGoMmp4jWzzPDRmIjNH7l5utWj6fDRZoyqRg06PY5DGsz3XRTMtvQrAG01NJB2VB0sCtBGb+FUxSfqvhPaSLMbswzWahEn6wKjvqEu3js7fSQ6EMZ9ChpMf4mhW5B/zcmN9BWIQCu1LJUnhUfOqlhvRTez7PP1z4RVjkwFZQBsWIlTz4WbmU98e8BB3f6BI++UGrqaIhYdIK32W+97/itjnxzXL6GmObKijw5d200cnt/VMWpNZ86OdlxC5LiJMmhM5MIFF6raIavOqaGgQ0O2VQTGtEuqkYD8N0NM9W8HX9RaMllLLM8IeLoZN1cbDKAgnYDSxL6wjV9JPUFEoRc0sqpupZjhQDSyvsvivpLSx7AQIQH77f+eJ5diAYH+HnVdqQYHDKm/Oihc+PzfzSJ6C5SwOQB8Wosqq2l2DgduU06XpISHFPTib4Z58NUC7B68SQ9cUFtb75EY0V6C6nTdzbosbGV8/yqPyZVp1htYybJHY+ct41mLDjAfCW7y2JqC9kkGpE7ipUmxxk5TmSdUFy8JEIBLDfIG7CUcpZb5csShB15mJeyGSlBOytsMONIIaQhKAm9mlgx4aVM/Xaqi5fQJhuoup8wg/PwVTEwQgY8r0oj0OXbI2oGvrcDpXh1ObyrP61DGuHvl6ec42+GxO14BpLPdG/31c2+M="


addons:
  sonarcloud:
    organization: "indicium"
    token:
      secure: "qM9k9yEyv+VA7WlILdlYdRyKZzWaa+b88wnihnMo3z0Ync1lvkIynljWeYfGYfGvMDnMO4upgWiEbU/Ks4Gmha+IMEuqDVFYTNY7HYO52s+P+MY01yuh0eOMSRJftYdFwQq7CZFXytenCb9ZgAQh8k2lVlkDOEFylT0WcGHOrgkaKRImD/5WrzJr2FlwdULxyJjkqgN8itNMKKbNjgcyTUMEhsAxc7yqAuX6CXSPK58gXU2G+GpThYhnSh+7zUZOfAfp9LzKjUdUPBGDqCpnUIM83FXG1vcEt0iy7iHQIBqvNttQEwC63Vi6MwsTTLbIBCmqnbzh8qdQ+1jmJaE9l63PONmoG/XpfDmYR6rELYtcCryjW+4wFYj2fcixu9+OVPQTHHuogApn8BK1kip1Vo0jno6FZlwHWRKw7D2MkdQaSAMNrsGL0A8jwJoZ6Rpz5/e/mTWCqMR1bYHJ6jmNqxVTxWy2OhJ1/ULMxJL/oXjSoIBF9wDMy5aLaixlJBpOkC3dRKIjTcf2sv9/o+5lgKNgTtrUSqF0KN1TmBjsrxtoee/EpXWXpmpB7zkcid1JdMJTleQuy/CxX80PCtXB4Q05VnOgw214BKCGoX8YM2Xa/kn7plJ0fViqcYx3+A3Byqfd877u85+1T7vYP4jDURMyZZPf+S7LhobI36LzWwY="


cache:
  npm: true

install:
  - npm install

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
  - echo "Skipping tests"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "stable"; elif [ "$TRAVIS_BRANCH" == "dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -t svindicium/website:$TAG .

deploy:
  provider: script
  script:
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
    docker push svindicium/website:$TAG;
  on:
    all_branches: true

